name: Data Pipeline CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run dbt tests
        run: |
          # We use env variables to safely pass the credentials
          dbt test --profiles-dir ./dbt_project
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          