version: '3.8'

services:
  postgres_warehouse:
    image: postgres:15-alpine
    container_name: local_postgres_warehouse
    environment:
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: "DB_PASSWORD"
      POSTGRES_DB: warehouse
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  data_pipeline:
    build: .
    container_name: python_pipeline_runner
    environment:
      - DB_HOST=postgres_warehouse
      - DB_PORT=5432
      - DB_USER=pipeline_user
      - DB_PASSWORD=DB_PASSWORD
      - DB_NAME=warehouse
    depends_on:
      - postgres_warehouse

volumes:
  postgres_data: