name: traffic_db
version: '1.0.0'

profile: traffic_db

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  traffic_db:
    staging:
      +materialized: view

    intermediate:
      +materialized: table

    marts:
      +materialized: table