name: 'ecommerce_dbt'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_profile' 

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  ecommerce_dbt:
    staging:
      +materialized: view  # <--- Ensure 2 or 4 spaces; NO TABS
    marts:
      +materialized: table