name: 'data_pipeline_ci_week8'
version: '1.0.0'
config-version: 2

profile: 'warehouse_profile'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Default configuration for models
models:
  data_pipeline_ci_week8:
    # Staging models are materialized as views
    staging:
      +materialized: view
    # Marts/Core models are materialized as tables
    marts:
      +materialized: table

# Configuration for seeds
seeds:
  data_pipeline_ci_week8:
    +column_types:
      id: integer
      customer_id: integer
      status: varchar(50)
      total_amount: numeric
      created_at: timestamp