\version: 2

models:
  - name: stg_vehicle_logs
    columns:

      - name: vehicle_id
        tests:
          - not_null

      - name: road_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: source('raw', 'road_segments')
                field: road_id

      - name: speed
        tests:
          - not_null